### PR TITLE
Fix for plugin upgrade

### LINKED ISSUE #616: Class not found on upgrade
**Describe the bug**
A problem loading a MQTT class is throwing when the plugin need an update

**To Reproduce**
1. Go to php command line and execute ```php tools\cli_install.php```
2. See error

**Expected behavior**
An upgrade for the plugin

**Screenshots**
imagen

### PR DESCRIPTION
**Pull request by DIOHz0r**
### Changes description

Update the plugin setup script which missed to include the autoloader on some status

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@DIOHz0r |4|

### References

Closes #616

### CODE REVIEW

File: setup.php [hunk 1]
```diff
@@ -90,8 +90,17 @@ function plugin_init_flyvemdm() {
       ]);
    }
 
-   if ($plugin->isActivated('flyvemdm')) {
+   if(!$plugin->getFromDBbyDir('flyvemdm')){
+      // nothing more to do at this moment
+      return;
```
Comment (btry) [inline setup.php]: I think you don't need to check if the method succeeded. GLPI automatically adds an entry in the DB if the plugin exists in the filesystem. The only case where a return will occur is when GLPI fails to write the row (mysql database with full filesystem or other severe failure not related to GLPI or its plugins)

File: inc/mqttclient.class.php [hunk 2]
```diff
@@ -282,7 +282,7 @@ protected function getMQTTConnection() {
    protected function buildMqtt($socketAddress, $port, $isTls, $sslCipher) {
       $protocol = $isTls ? "ssl://" : "tcp://";
       try {
-         $mqtt = new sskaje\mqtt\MQTT("$protocol$socketAddress:$port");
+         $mqtt = new \sskaje\mqtt\MQTT("$protocol$socketAddress:$port");
```
Comment (btry) [inline inc/mqttclient.class.php]: you can remove this change.

File: setup.php (hunk 1 above)
Comment (DIOHz0r) [reply setup.php]: There are two checks, the first one is for not execute the rest of the checks because if that query return false and I don't check it, the autoload load will be include by the reason of the field state will return N/A which will be different of NOTACTIVATED
