### PR TITLE
Some MQTT topics are not cleaned up

### LINKED ISSUE #285: Get unrollment message for every email
#### Observed Results:
Testing the unenroll policy with the new topics, always get `{"unenroll":"now"}` on the agent with any email, these are the steps to reproduce the bug:

- Enroll device with email "A"
- Send unenroll policy from dashboard
- Get unenroll policy on the agent

- Enroll a device with email "B"
- get unenroll policy

- Enroll a device with email "C"
- get unenroll policy

### PR DESCRIPTION
**Pull request by btry**
### Changes description

fix wrong merge of two arrays

### Checklist

Please check if your PR fulfills the following specifications:

- [x] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #285

### CODE REVIEW

File: tests/suite-unit/PluginFlyvemdmAgent.php [hunk 1]
```diff
@@ -219,4 +219,64 @@ public function testCanViewItem() {
...
+         'Command/Ping',
+         'Command/Geolocate',
+         'Command/Inventory',
+         'Command/Lock',
+         'Command/Wipe',
+         'Command/Unenroll',
+
+         // Policies
+         'Policy/passwordEnabled',
+         'Policy/passwordMinLength',
```
Comment (DIOHz0r) [inline tests/suite-unit/PluginFlyvemdmAgent.php]: Is not there a better way to manage this? I mean if the policies grow this will need it too.

Comment (btry) [reply tests/suite-unit/PluginFlyvemdmAgent.php]: Yes and I explicitly want this. The purpose is that every topics are actually cleaned up. This is important enough to be checked IMO.
